name: 'Tag Users that Reacted with an Emoji'
description: 'This action tags users who reacted with a specific emoji on GitHub Issues or Pull Requests.'
inputs:
  emoji:
    description: 'The emoji to look for in reactions.'
    required: true
  message:
    description: 'The customizable message to include at the beginning of the comment.'
    required: false
runs:
  using: 'node20'
  main: 'src/index.js'